site_name: Taller de Godot (C.E. Desarrollo de Videojuegos Y Realidad Virtual)
theme: 
  logo: img/godotlogo.png
  favicon: img/godotlogo.png
  name: material
  features:
    - header.autohide
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - Home: index.md
  - Introducción:
      - Introducción: intro.md
      - Requisitos: req.md
  - Instalación:
      - Instalación de Godot: install.md
  - Primeros pasos:
      - Primeros pasos: firststeps.md
  - Interfaz:
      - Interfaz de Godot: interface.md
  - Escenas:
      - Escenas: scenes.md
  - Nodos:
      - Nodos: nodes.md
  - ShotemUp (2D):
      - Introducción al ShotemUp: shotemup.md
      - Escena Principal: main_scene.md
      - Jugador: character.md
      - Movimiento: movement.md
      - Enemigo: enemy.md
      - Respawn Enemigos: respawn_enemies.md
      - Disparos: shots.md
      - Colisiones: collisions.md
  - 3D:
      - Introducción a 3D: intro_3d.md
      - Luces, Camara y Nodos: lights_camera_nodes.md
      - Nodos 3D vs Nodos 2D: nodes_3d_vs_2d.md
      - GDash (Juego de plataformas 3D): 
          - Juego Plataformas 3D: gdash.md
          - Creación de Terreno: terrain.md
          - Jugador: player.md
          - Movimiento: movement_3d.md
          - Trampas: traps.md
          - Fin de la partida: game_over.md
    
  - VR:
      - Introducción a VR: intro_vr.md
  - Recursos: resources.md