site_name: Taller de Godot (C.E. Desarrollo de Videojuegos Y Realidad Virtual)
theme: 
  logo: img/godotlogo.png
  favicon: img/godotlogo.png
  name: material
  features:
    - header.autohide
extra_css:
  - css/custom.css
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - Home: index.md
  - Introducción:
      - Introducción: intro.md
      - Requisitos: req.md
  - Instalación:
      - Instalación de Godot: install.md
  - Primeros pasos:
      - Primeros pasos: firststeps.md
  - Interfaz:
      - Interfaz de Godot: interface.md
  - Escenas:
      - Escenas: scenes.md
  - Nodos:
      - Nodos: nodes.md
  - ShotemUp (2D):
      - Introducción al ShotemUp: shotemup.md
      - Escena Principal: main_scene.md
      - Jugador: character.md
      - Movimiento: movement.md
      - Enemigo: enemy.md
      - Respawn Enemigos: respawn_enemies.md
      - Disparos: shots.md
      - Colisiones: collisions.md
  - 3D:
      - Introducción a 3D: 3d/intro_3d.md
      - Luces, Camara y Nodos: 3d/lights_camera_nodes.md
      - Nodos 3D vs Nodos 2D: 3d/nodes_3d_vs_2d.md
      - GDash (Juego de plataformas 3D): 
          - Juego Plataformas 3D: 3d/gdash.md
          - Creación del Proyecto: 3d/create_project.md
          - Creación de Terreno: 3d/terrain.md
          - Jugador: 3d/player.md
          - Movimiento: 3d/movement_3d.md
          - Trampas: 3d/traps.md
          - Fin de la partida: 3d/game_over.md
          - UI: 3d/ui.md
          - Win: 3d/win.md
    
  - VR:
      - Introducción a VR: intro_vr.md
  - Recursos: resources.md